---
abstract: 'plugin system for HTML::Lint'
author:
  - 'Kenta Sato <karupa@cpan.org>'
build_requires:
  Module::Build::Pluggable::ReadmeMarkdownFromPod: 0.04
  Module::Build::Pluggable::Repository: 0.01
  Pod::Markdown: 0
  Test::More: 0.88
  Test::Requires: 0.06
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
  Module::Build::Pluggable: 0.04
  Module::Build::Pluggable::ReadmeMarkdownFromPod: 0.04
  Module::Build::Pluggable::Repository: 0.01
dynamic_config: 0
generated_by: 'Minilla/v0.6.4, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Lint-Pluggable
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  HTML::Lint::Pluggable:
    file: lib/HTML/Lint/Pluggable.pm
    version: 0.03
  HTML::Lint::Pluggable::HTML5:
    file: lib/HTML/Lint/Pluggable/HTML5.pm
    version: 0.03
  HTML::Lint::Pluggable::TinyEntitesEscapeRule:
    file: lib/HTML/Lint/Pluggable/TinyEntitesEscapeRule.pm
    version: 0.03
  HTML::Lint::Pluggable::WhiteList:
    file: lib/HTML/Lint/Pluggable/WhiteList.pm
    version: 0.03
requires:
  Carp: 0
  Class::Load: 0
  HTML::Entities: 0
  HTML::Lint: 0
  List::MoreUtils: 0
  parent: 0
  perl: 5.009_004
resources:
  bugtracker: https://github.com/karupanerura/p5-HTML-Lint-Pluggable/issues
  homepage: https://github.com/karupanerura/p5-HTML-Lint-Pluggable
  repository: git://github.com/karupanerura/p5-HTML-Lint-Pluggable.git
version: 0.03
